# Jersuxs's Home Configuration
# For support, join our Discord Server: https://discord.gg/Q2NWpZFGUQ

# Language settings
language:
  # Current language (en = English, es = Spanish)
  current: "en"
  # Available languages
  available:
    - "en" # English
    - "es" # Spanish
    - "fr" # French
    - "pt" # Portuguese
    - "de" # German
    - "ru" # Russian
    - "zh_cn" # Simplified Chinese
    - "zh_tw" # Traditional Chinese


# Maximum homes per player (0 = unlimited)
max-homes: 5

# Teleport delay time (seconds)
teleport-delay: 3

# Effects when teleporting
teleport-effects:
  particles: true
  sound: true

# World-specific permissions
world-permissions:
  world: true
  world_nether: true
  world_the_end: true